### ISSUE TITLE
PINURLSessionManager.m:210 There seems to be an issue in iOS 9 where this can be nil. If you can reliably reproduce hitting this, *please* open an issue: https://github.com/pinterest/PINRemoteImage/issues

### ISSUE THREAD

**Issue by itunescn** [pinterest/PINRemoteImage#533] opened 2019-10-22 13:47 UTC
![Screen Shot 2019-10-22 at 9 46 07 PM](https://user-images.githubusercontent.com/12559006/67292275-6474b800-f515-11e9-8609-fcd508093246.png)

**Comment by garrettmoon** [comment] 2019-12-19 21:07
@itunescn if you're able to reliably reproduce this, please post a sample project!

**Comment by garrettmoon** [comment] 2020-01-15 23:23
Going to close this since there hasn't been a reply.

**Closed by garrettmoon** 2020-01-15 23:23 UTC
Labels: close if no reply

**Comment by VitaliiVasylyda** [comment] 2020-02-12 20:08
Good evening we have the same issue on our project, 100% reproduce on iOS 10.3. Here a message from the console  Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'There seems to be an issue in iOS 9 where this can be nil. If you can reliably reproduce hitting this, *please* open an issue: https://github.com/pinterest/PINRemoteImage/issues'.

**Comment by Daemonson** [comment] 2021-02-20 10:05
Hey there, the example project of repo [Texture](https://github.com/texturegroup/texture) can reproduce this crash. 

Download the repo, you can find out the example project in this file path: Texture-master/examples_extra/ASDKgram-Swift.

Running the project and then scroll the view as fast as you can in the ASDK tab. Now you can encounter this assertion caused by the nil value of the delegateQueue.

My Xcode version is 12.4 (12D4e).  The device is an iPod touch 6 on iOS 10.3.3.
