### ISSUE TITLE
Error with overloaded methods

### ISSUE THREAD

**Issue by mdamicoml** [pinterest/PINRemoteImage#532] opened 2019-10-03 19:44 UTC
I tried to update to '3.0.0-beta.10' from 'release 2.1.4' but it crashed with error:

`Conflicting parameter types in declaration of 'setObjectAsync:forKey:completion:': 'id  _Nonnull __strong' vs 'id<NSCoding>  _Nonnull __strong'`

The problem it's about overloading methods like "setObjectAsync", "setObjectAsync", "setObjectAsync" that are in the "PINCaching" interface.

**Comment by garrettmoon** [comment] 2019-12-19 21:10
@mdamicoml I'm not sure I understand, do you mind posting a sample project which reproduces?

**Comment by garrettmoon** [comment] 2020-01-15 23:23
Going to close this since there hasn't been a reply.

**Closed by garrettmoon** 2020-01-15 23:23 UTC
Labels: close if no reply
