### ISSUE TITLE
Bad Config: this repo doesn't understand carthage command

### ISSUE THREAD

**Issue by lastcc** [pinterest/PINRemoteImage#422] opened 2017-10-25 08:35 UTC
Command:

     carthage update --platform ios

However tvOS and macOS counterparts are also produced.

And this repo doesn't show up in Checkouts folder?

**Comment by garrettmoon** [comment] 2017-10-25 18:35
@lastcc Can you provide more info and possibly a sample project? I'm not entirely sure what the issue is. I'm sadly not a Carthage expert :(

**Comment by lastcc** [comment] 2017-10-26 09:47
@garrettmoon Hi thanks for the reply. Will reply with more details tomorrow. :)

**Comment by lastcc** [comment] 2017-10-28 14:59
@garrettmoon 

Hi I was reading source code and totally forgot the issue.

there is a bug in `insertImageDataIntoCache` In source code:

```swift
PINRemoteImageManagerDownloadOptions options = PINRemoteImageManagerDownloadOptionsSkipDecode & PINRemoteImageManagerDownloadOptionsSkipEarlyCheck;
```

the option is none because the `&`. i'm in the master branch i think.

**Comment by lastcc** [comment] 2017-10-28 15:02
@garrettmoon 
https://github.com/pinterest/PINRemoteImage/blob/0aec6d2bef2a720636044ff7cfa6947f42270ccb/Source/Classes/PINRemoteImageManager.m#L799

**Comment by garrettmoon** [comment] 2017-10-30 20:34
I'm going to close this since you opened a new issue.

**Closed by garrettmoon** 2017-10-30 20:34 UTC
