### ISSUE TITLE
Crash because of observing state

### ISSUE THREAD

**Issue by hovox** [pinterest/PINRemoteImage#409] opened 2017-09-18 06:41 UTC
We are getting crashes, [here](http://crashes.to/s/161da86a976) is the fabric link. After investigation we have found that the crash is because of observing `state` property of the `NSURLSessionTask`. Here is the [line](https://github.com/pinterest/PINRemoteImage/blob/master/Source/Classes/Categories/NSURLSessionTask+Timing.m#L33). We have forked an commented out this classes methods as a temporary solution. As I remember that crash has been fixed in AFNetworking with swizzling, but I think it's better to not observe that property and achieve same without swizzling.  What you would suggest as an alternative solution to fix this crash? 

Thanks.

**Comment by garrettmoon** [comment] 2017-09-18 16:28
Dupe of #390

**Comment by garrettmoon** [comment] 2017-09-18 16:29
@hovox take a look at #406 for current discussion on this issue.

**Closed by garrettmoon** 2017-09-18 16:28 UTC
