### ISSUE TITLE
Not able to export tvOS framework with Carthage.

### ISSUE THREAD

**Issue by mobileexpert1** [pinterest/PINRemoteImage#195] opened 2016-05-02 11:08 UTC
When i do this: github "pinterest/PINRemoteImage"
carthage update --platform tvOS
It always export frameworks for iOS and mac os.

When i use github "pinterest/PINRemoteImage" ~> 3.0
It shows an error : A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/mobile/Desktop/Carthage/Checkouts/PINRemoteImage/Example-Mac/PINRemoteImage.xcworkspace -scheme PINRemoteImage -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme PINRemoteImage is not currently configured for the build action.

![screen shot 2016-05-02 at 4 37 46 pm](https://cloud.githubusercontent.com/assets/9291694/14953139/437fbc18-1084-11e6-8c48-29766da42966.png)

**Comment by zachwaugh** [comment] 2016-11-11 21:12
I hit this as well, doesn't seem to be specific to the tvOS target, but carthage 0.18.1 doesn't work at all right now with 3.0 beta:

```
*** Fetching PINRemoteImage
*** Fetching PINCache
*** Downloading PINCache.framework binary at "3.0.1 Beta 2"
*** Checking out PINRemoteImage at "3.0.0-beta.6"
*** xcodebuild output can be found in /var/folders/4x/k22fcvxj09q33bnxlpc1ngv00000gn/T/carthage-xcodebuild.D68Rup.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/zach/code/tmp/CarthageTest/Carthage/Checkouts/PINRemoteImage/Example-Mac/PINRemoteImage.xcworkspace -scheme PINRemoteImage -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme PINRemoteImage is not currently configured for the clean action.
```

That seems to be a carthage issue though, related to how it figures out which frameworks to build. I opened [PR](https://github.com/Carthage/Carthage/pull/1572) to fix it, but there is another issue with PINRemoteImage. The `Example-Mac` and `Example-tvOS` projects don't build correctly, so carthage will fail there as well.

```
The following build commands failed:
	CompileC /Users/zach/Library/Developer/Xcode/DerivedData/PINRemoteImage.tvOSExample-dgehkxqahxflddbhvmhmsxrbvjto/Build/Intermediates/Pods.build/Release-appletvos/Pods-PINRemoteImage.tvOSExample-PINRemoteImage.build/Objects-normal/arm64/PINRemoteImageManager.o /Users/zach/code/tmp/CarthageTest/Carthage/Checkouts/PINRemoteImage/Pod/Classes/PINRemoteImageManager.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/zach/code/tmp/CarthageTest/Carthage/Checkouts/PINRemoteImage/Pod/Classes/PINRemoteImageManager.m:30:9: fatal error: 'PINCache+PINRemoteImageCaching.h' file not found
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/zach/code/tmp/CarthageTest/Carthage/Checkouts/PINRemoteImage/Example-tvOS/PINRemoteImage.tvOSExample.xcworkspace -scheme Pods-PINRemoteImage.tvOSExample-PINRemoteImage -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

Same thing if you try to build the example in Xcode, so there seems to be something busted with how those example projects are setup. I'm not familiar enough with the specific configuration for those example projects to fix. The iOS example project works fine.

![image](https://cloud.githubusercontent.com/assets/21447/20230332/6a64c28c-a829-11e6-92ce-d7a98fa62344.png)

**Comment by garrettmoon** [comment] 2016-11-11 22:20
I try my best to keep carthage working, but we don't use it internally. If you could put up PRs to fix or give me instructions, I'd be happy to help!

**Comment by zachwaugh** [comment] 2016-11-11 22:28
The first issue is with carthage itself, so you can ignore that one. For the second issue I mentioned, you can reproduce it without carthage. Open the *Example-Mac* and *Example-tvOS* workspaces, and try to build either directly from Xcode, and the fail with the error above. Carthage tries to build all dynamic frameworks it finds in the repo, so if any fail, the whole thing fails. Unfortunately, carthage doesn't currently have a few to specify which schemes/frameworks to build.

**Comment by sirvon** [comment] 2017-02-26 13:50
so...we cant' use this or any lib that depends on this lib with carthage?

**Comment by garrettmoon** [comment] 2017-02-27 18:15
@sirvon not with apple tv currently, looking for a volunteer to improve it! Happy to accept pull requests!

**Comment by garrettmoon** [comment] 2017-02-27 18:16
Actually, I would think this *would* work on Apple TV currently with master now. Just not mac likely :(

**Comment by zachwaugh** [comment] 2017-02-28 15:37
This appears to be working now. The problem previously was that carthage failed to build due to the example project, this seems to have since been fixed. I don't have an Apple TV app to test with, but using Carthage 0.19.1 on master and it builds the tvOS framework now:

```
~/code/tmp/CarthageTest: cat Cartfile
github "pinterest/PINRemoteImage" "master"
~/code/tmp/CarthageTest: carthage bootstrap
*** Please update to the latest Carthage version: 0.20.0. You currently are on 0.19.1
*** No Cartfile.resolved found, updating dependencies
*** Fetching PINRemoteImage
*** Fetching PINOperation
*** Checking out libwebp at "v0.5.1"
*** Checking out PINOperation at "1.0.3"
*** Downloading PINCache.framework binary at "3.0.1 Beta 4"
*** Checking out PINRemoteImage at "a5ac670cac32ceebbd9b5d4aa6841dcef013bc70"
*** xcodebuild output can be found in /var/folders/rx/ctk8gsx943v6rq57q0b_35fr0000gn/T/carthage-xcodebuild.Llezrh.log
*** Building scheme "PINOperation" in PINOperation.xcodeproj
*** Building scheme "PINOperation-macOS" in PINOperation.xcodeproj
*** Building scheme "PINOperation-tvOS" in PINOperation.xcodeproj
*** Building scheme "PINRemoteImage" in PINRemoteImage.xcodeproj
~/code/tmp/CarthageTest:
```

**Comment by garrettmoon** [comment] 2017-02-28 18:05
Great! Refactoring the project layout payed off! Going to close this for now.

**Closed by garrettmoon** 2017-02-28 18:05 UTC
Labels: needs volunteer
