### ISSUE TITLE
Set FLAnimatedImage as an optional dependency

### ISSUE THREAD

**Issue by lexrus** [pinterest/PINRemoteImage#35] opened 2015-08-10 09:51 UTC
Since they don't update FLAnimatedImage for a while. The [issues list](https://github.com/Flipboard/FLAnimatedImage/issues) just getting longer. And it's [not compatible with Swift project](https://github.com/Flipboard/FLAnimatedImage/issues/75). I'd recommend set FLAnimatedImage as an optional dependency.

**Comment by garrettmoon** [comment] 2015-08-10 19:55
This is a duplicate of #22

**Closed by garrettmoon** 2015-08-10 19:55 UTC
