### ISSUE TITLE
Crash on [PINAnimatedImage frameCount]

### ISSUE THREAD

**Issue by zjmdp** [pinterest/PINRemoteImage#389] opened 2017-07-10 06:02 UTC
v3.0.0-beta.11

crash log:
http://crashes.to/s/c0f8fc7c80e

**Comment by garrettmoon** [comment] 2017-07-21 22:23
@zjmdp Are you displaying multiple GIFs at once? That's currently a known issue I haven't had time to look into.

**Comment by zjmdp** [comment] 2017-07-24 02:30
YES, I have multiple GIFs on the same page.

**Comment by garrettmoon** [comment] 2017-07-26 17:21
Yeah, sadly this is probably a duplicate of https://github.com/pinterest/PINRemoteImage/issues/203

**Closed by garrettmoon** 2017-07-26 17:21 UTC

**Comment by PatrickSCLin** [comment] 2017-09-27 03:08
any solutions to avoid or reduce this happen ?

**Comment by garrettmoon** [comment] 2017-09-28 17:14
I've completely rewritten GIF support, hopefully it will be landing soonish: https://github.com/pinterest/PINRemoteImage/pull/411
