### ISSUE TITLE
Image scale is always 1.0

### ISSUE THREAD

**Issue by rounak** [pinterest/PINRemoteImage#152] opened 2016-02-25 23:20 UTC
The images created by PINRemoteImage always has a scale of 1.0, which causes problems with intrinsic sizes of image views. SDWebImage create images with the correct scale factor depending on the device.

**Comment by garrettmoon** [comment] 2016-03-02 16:36
Thanks for the report @rounak, definitely something we should look into addressing!

**Comment by rounak** [comment] 2016-03-03 09:37
@garrettmoon This is the fix we added https://github.com/TinderApp/PINRemoteImage/commit/bea7c9d6636e392b6b2b5a0809bf13629b0d0fc9 We didn't use `UIScreen scale` because we weren't sure if that can be called from non main threads. Let me know if you think this is a good fix. If so, I can open up a PR

**Comment by garrettmoon** [comment] 2016-04-28 22:37
@rounak Thanks for bringing this up and figuring out a solution!

I think this should probably be done at a different layer, or specified at a different layer. All the images that are downloaded from the web don't have 'scale' per say as far as I know. So this would set the scale arbitrarily to the screen size. I'm not sure what the effects would be for people relying on the scale being 1.0 currently.

Since scale is generally used by UIImageView, it seems like this sort of abstraction would live better there. Would it be better to have the UIImage modified in pin_updateUIWithRemoteImageManagerResult in PINImageView+PINRemoteImage?

We could add a bool which indicates whether images should be 'scaled' and if so, create a new UIImage
```
NSAssert(resultImage.CGImage, @"UIImage must have CGImage backing");
[UIImage imageWithCGImage:[resultImage CGImage] scale:[self contentScaleFactor] orientation:[resultImage orientation]]
```

Alternatively, the scale could be something that is set on the PINRemoteImageManager, but I think it makes more sense to be part of the view's.

What do you think?

**Comment by rounak** [comment] 2016-05-02 20:03
@garrettmoon Agreed that the current layer where this is done seems a little off. However, if we just put it in the image view category, places where images are prefetched, or where we're directly using the image manager would be excluded. So I think PINRemoteImageManager seems like a better candidate to add that.

One thing to note is that UIImage size is measured in points and not pixels. So as per Apple's docs, to get the actual size in pixels of an image, you should always multiple size by scale.
![screen shot 2016-05-02 at 1 02 52 pm](https://cloud.githubusercontent.com/assets/240258/14966241/392bc82e-1066-11e6-9108-15ceeaa268d7.png)

**Comment by matrixx** [comment] 2016-06-20 09:11
Hi! Just bumped into the same issue. What's the status of the upcoming fix?

**Comment by garrettmoon** [comment] 2016-06-20 17:41
@matrixx @rounak I'm ok with this integrating at the manager layer if we can get something in before 3.0. However, I'd rather it be configurable instead of just using the main screen's scale.

**Comment by matrixx** [comment] 2016-06-22 13:00
Great! I'll be following this.

**Comment by SuperTango** [comment] 2017-02-03 18:31
Has there been any changes related to this?  Using a scale of 1.0 makes the pictures look janky on almost any modern iOS device.

**Comment by garrettmoon** [comment] 2017-02-03 18:46
@SuperTango Nope, no one has put up a new PR and it's not affecting us at Pinterest so it's not at the top of our priority list. Happy to work with someone to assist them in developing a PR however.

**Comment by maicki** [comment] 2017-02-09 17:45
The problem is that currently PINRemoteImage in pin_decodedImageWithData:skipDecodeIfPossible is decoding image data always with a scale of 1.0. This is most of the time the right way as images are served in 1x. The problem appears if retina images are served from the server like @2x or @3x images. The decoding of this image data will produce not the right result.

One of the possible solutions that were proposed was something like this:

```
CGImageRef newImage = CGBitmapContextCreateImage(ctx);
UIImage *decodedImage = [UIImage imageWithCGImage:newImage scale:UIScreen.mainScreen.scale orientation:orientation];
```

As mentioned above this is not the right solution for all cases as images are usual served as a scale of 1x.

I think there are two ways we should provide support for that:
1. Add support to PINRemoteImage that if images URLs contain a `@2x` or `@3x` in the URL it will be automatically scaled
2. Add to the documentation if the first way is not working there is still another way to archive that within the completion handler of setting the URL of e.g an `UIImageView`:
```
__weak UIImageView *weakImageView = self.imageView;
[self.imageView pin_setImageFromURL: [NSURL URLWithString:@"https://placekitten.com/801/801"] completion:^(PINRemoteImageManagerResult * _Nonnull result) {
  CGFloat scale = UIScreen.mainScreen.scale;
  if (scale > 1.0) {
    UIImage *image = result.image;
    weakImageView.image = [UIImage imageWithCGImage:image.CGImage scale:scale orientation:image.imageOrientation];
    }
}];
```

**Comment by garrettmoon** [comment] 2017-02-11 00:07
Going to close this issue, I think @maicki's PR should address this.

**Closed by garrettmoon** 2017-02-11 00:07 UTC
Labels: enhancement
