### ISSUE TITLE
[WebP] Add support for animated WebP images.

### ISSUE THREAD

**Issue by wlegate** [pinterest/PINRemoteImage#289] opened 2016-12-15 02:42 UTC
WebP supports animated "photos" as well which are essentially GIFs but at a fraction of the file size & at a higher resolution. Any plans on supporting this in the future? If not, happy to look into creating a PR

**Comment by wlegate** [comment] 2016-12-15 02:46
Didn't see that this is already supported

**Comment by appleguy** [comment] 2016-12-15 05:27
@wlegate We would love to support this!  It's been discussed, but unfortunately, we lack the resources to prioritize this particular area in the near future.  If you did put up a PR, we'd be able to support reviewing it and would give feedback to converge on landing it!

That said, it would be very important to make the libwebp dependency an optional one.  The .podspec configuration already shows how to do this for one other project I believe.  Also, AsyncDisplayKit supports this in how it includes PINRemoteImage, although it's included by default.

Ideally, if you do investigate this, it would be great if you could do it in the context of both non-ASDK and ASDK users.  There's a generic image animation protocol in ASDK that ties in with PINRemoteImage already (for GIF) support, and it was designed with future WebP support in mind, so it should be feasible.  The great thing about supporting ASDK with this is that it allows async decoding to be triggered before the content is onscreen, and can clean up these large-memory items when they start moving too far offscreen, so having support for WebP there would make for a great companion to any app with WebP needs in production.

**Comment by dalu93** [comment] 2017-04-04 09:29
+1 interested in this feature

**Comment by was0107** [comment] 2017-09-05 09:08
+1

**Comment by appleguy** [comment] 2017-09-09 03:07
@garrettmoon - my team also has a use case for this now (we’d love to benefit from Texture + PINRemoteImage prefetching and async decoding, because FLAnimatedImage is not resulting in good performance).

If anyone in the community is interested in developing this, it looks like plenty of people would benefit from your work!

**Comment by dustfire** [comment] 2017-09-13 20:55
hey @appleguy we are planning to use this as well @ Giphy -- love to help

**Comment by garrettmoon** [comment] 2017-09-13 21:57
@dustfire I'm happy to help with architectural suggestions and code review if you're willing to take up the actual development work. Feel free to send me an email for faster response if you're interested (garrett@pinterest.com).

**Comment by garrettmoon** [comment] 2018-05-24 17:02
This is done on master!

**Closed by garrettmoon** 2018-05-24 17:02 UTC
Labels: enhancement
